from setuptools import setup

required_libraries = [
    "allennlp",
    "beautifulsoup4",
    "convoys",
    "cycler",
    "faker",
    "flair",
    "gensim==3.4.0",
    "geopandas",
    "google_compute_engine",
    "html2text",
    "jupyter",
    "kiwisolver",
    "matplotlib",
    "numpy",
    "google_compute_engine",
    "pandas",
    "prettytable",
    "pyparsing",
    "pyspark",
    "python-dateutil",
    "pytorch-pretrained-bert>=0.6.0",
    "pytz==2017.3",
    "pyproj",
    "regex==2018.01.10",
    "requests",
    "seaborn",
    "scikit-learn",
    "scikit-optimize",
    "scipy",
    "six",
    "statsmodels",
    "torch==1.0.0",
    "tqdm==4.26.0",
    "wrapt==1.10.0",
]

setup(
    name="feet",
    version="0.1",
    description="a declarative feature engineering pipeline based on sklearn",
    url="http://github.com/jattenberg/feet",
    author="jattenberg",
    author_email="josh@attenberg.org",
    license="MIT",
    packages=["feet", "tests"],
    zip_safe=False,
    install_requires=required_libraries,
)
